projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - packages/frontend/src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: packages/frontend/src/API.ts
        docsFilePath: packages/frontend/src/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
